### ISSUE TITLE
Is screen scraping still supposed to work?

### ISSUE THREAD

**Issue by exactt** [skleinei/collmex-api#1]
Hi,

I just took my first steps using this library. If I set screenScrapingEnabled to true I get exceptions thrown while the "Angebot" is created successfully. So before I start digging deeper I just wanted to know if it is still supposed to work? Last commit was 10 months ago...

Thx!

**Comment by skleinei** [comment]
Yeah, long time ago. The screen scraping is not needed anymore, as Collmex has extended the fields provided by their API. However, this is not implemented in this library yet.

If you fancy a PR, I'd love to accept it.

**Comment by skleinei** [comment]
I've just pushed a commit that removes screen scraping (and a few unneeded libraries).
